export interface DepartmentGroup {
  id: string;
  group: string;
  departments: string[];
  math: string;
  subject1: string;
  subject2: string;
}

export const groupsData: DepartmentGroup[] = [
  {
    id: "g1",
    group: "機械群",
    departments: ["機械製圖科", "機械科", "配管科", "模具科", "板金科", "鑄造科", "重機科"],
    math: "數學（C）",
    subject1: "機件原理、機械力學",
    subject2: "機械製造、機械基礎實習、機械製圖實習",
  },
  {
    id: "g2",
    group: "動力機械群",
    departments: ["汽車科", "重機科"],
    math: "數學（C）",
    subject1: "應用力學、引擎、底盤原理",
    subject2: "引擎實習、底盤實習、電子電工實習",
  },
  {
    id: "g3",
    group: "電機與電子群 - 電機類",
    departments: ["電機科", "冷凍科", "控制科"],
    math: "數學（C）",
    subject1: "基本電學、電子學、基本電學實習、電子學實習",
    subject2: "電工機械、電工機械實習",
  },
  {
    id: "g4",
    group: "電機與電子群 - 資電類",
    departments: ["電子科", "資訊科", "控制科"],
    math: "數學（C）",
    subject1: "基本電學、電子學、基本電學實習、電子學實習",
    subject2: "微處理機、數位邏輯設計、程式設計實習",
  },
  {
    id: "g5",
    group: "化工群",
    departments: ["化工科"],
    math: "數學（C）",
    subject1: "基礎化工、化工裝置",
    subject2: "普通化學、普通化學實習、分析化學、分析化學實習",
  },
  {
    id: "g6",
    group: "土木與建築群",
    departments: ["土木科", "建築科"],
    math: "數學（C）",
    subject1: "基礎工程力學、材料與試驗",
    subject2: "測量實習、製圖實習",
  },
  {
    id: "g7",
    group: "設計群",
    departments: ["圖傳科", "廣設科", "室設科", "美工科"],
    math: "數學（B）",
    subject1: "色彩原理、造形原理、設計概論",
    subject2: "基本設計（術科實作）、繪畫基礎（術科實作）、基礎圖學（術科實作）",
  },
  {
    id: "g8",
    group: "工程與管理類",
    departments: ["工科學生可報考"],
    math: "數學（C）",
    subject1: "物理(B)",
    subject2: "資訊科技",
  },
  {
    id: "g9",
    group: "商業與管理群",
    departments: ["資處科", "商經科", "會計科", "國貿科"],
    math: "數學（B）",
    subject1: "商業概論、數位科技概論及應用",
    subject2: "會計學、經濟學",
  },
  {
    id: "g10",
    group: "餐旅群",
    departments: ["餐旅科", "觀光科"],
    math: "數學（B）",
    subject1: "觀光餐旅與導論",
    subject2: "餐旅服務技術、餐飲實務",
  },
  {
    id: "g11",
    group: "外語群 - 英語類",
    departments: ["應用外語英文科"],
    math: "數學（B）",
    subject1: "商業概論、數位科技概論及應用",
    subject2: "英文閱讀與寫作",
  },
  {
    id: "g12",
    group: "外語群 - 日語類",
    departments: ["應用外語日文科"],
    math: "數學（B）",
    subject1: "商業概論、數位科技概論及應用",
    subject2: "日文閱讀與翻譯",
  },
  {
    id: "g13",
    group: "食品群",
    departments: ["食品加工科"],
    math: "數學（B）",
    subject1: "食品加工、食品加工實習",
    subject2: "食品化學與分析、食品化學與分析實習",
  },
  {
    id: "g14",
    group: "農業群",
    departments: ["園藝科"],
    math: "數學（B）",
    subject1: "生物(B)",
    subject2: "農業概論",
  },
  {
    id: "g15",
    group: "衛生與護理類",
    departments: ["護理科"],
    math: "數學（A）",
    subject1: "生物(B)",
    subject2: "健康與護理",
  },
  {
    id: "g16",
    group: "家政群 - 幼保類",
    departments: ["美容科", "家政科", "幼保科"],
    math: "數學（A）",
    subject1: "家政概論、家庭教育",
    subject2: "嬰幼兒發展照護實務",
  },
  {
    id: "g17",
    group: "家政群 - 生活應用類",
    departments: ["美容科", "家政科", "幼保科"],
    math: "數學（A）",
    subject1: "家政概論、家庭教育",
    subject2: "多媒體創作實務",
  },
  {
    id: "g18",
    group: "海事群",
    departments: ["輪機科"],
    math: "數學（B）",
    subject1: "船藝",
    subject2: "輪機",
  },
  {
    id: "g19",
    group: "水產群",
    departments: ["水產養殖科"],
    math: "數學（B）",
    subject1: "水產概要",
    subject2: "水產生物實務",
  },
  {
    id: "g20",
    group: "藝術群 - 影視類",
    departments: ["表演藝術科", "影視科"],
    math: "數學（A）",
    subject1: "藝術概論",
    subject2: "展演實務、音像藝術展演實務",
  },
];
